name: front_matter_ml
version: 1.2.0
description: A front matter parser that extracts YAML metadata from the start of a file or string.
homepage: https://github.com/maks/front_matter_ml
documentation: https://github.com/maks/front_matter_ml/blob/master/README.md
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.4
